# Generated by Django 4.2.13 on 2026-03-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_producto_categoria_producto_tienda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='factura_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
