# Generated by Django 4.2.13 on 2026-03-23 00:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_pedido_factura_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('numero_guia', models.CharField(blank=True, default='', max_length=80)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='ecommerce.pedido')),
            ],
        ),
    ]
