# Generated by Django 4.2.13 on 2026-03-25 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_reseña'),
        ('ecommerce', '0007_perfilusuario_nombre_perfilusuario_direccion_and_envio'),
    ]

    operations = [
    ]
