# Generated by Django 4.2.13 on 2026-04-19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_merge_20260325_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='calificacion',
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'activo'], name='ecommerce_p_catego_12f799_idx'),
        ),
    ]
