# Generated by Django 4.2.13 on 2026-04-19

from django.db import migrations, models
import django.db.models.deletion


def migrate_categoria_to_fk(apps, schema_editor):
    Producto = apps.get_model('ecommerce', 'Producto')
    Categoria = apps.get_model('ecommerce', 'Categoria')

    nombres = (
        Producto.objects
        .exclude(categoria__isnull=True)
        .values_list('categoria', flat=True)
        .distinct()
    )

    categorias_map = {}
    for nombre in nombres:
        clean_name = (nombre or '').strip()
        if not clean_name:
            continue
        categoria_obj, _ = Categoria.objects.get_or_create(nombre=clean_name)
        categorias_map[clean_name] = categoria_obj

    for producto in Producto.objects.all().iterator():
        clean_name = (producto.categoria or '').strip()
        categoria_obj = categorias_map.get(clean_name)
        producto.categoria_fk = categoria_obj
        producto.save(update_fields=['categoria_fk'])


def rollback_categoria_to_text(apps, schema_editor):
    Producto = apps.get_model('ecommerce', 'Producto')

    for producto in Producto.objects.select_related('categoria_fk').all().iterator():
        producto.categoria = producto.categoria_fk.nombre if producto.categoria_fk else ''
        producto.save(update_fields=['categoria'])


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_resena_rating_and_producto_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='ecommerce_p_catego_12f799_idx',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='ecommerce.categoria'),
        ),
        migrations.RunPython(migrate_categoria_to_fk, rollback_categoria_to_text),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_fk',
            new_name='categoria',
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'activo'], name='ecommerce_p_catego_12f799_idx'),
        ),
    ]
