# Generated by Django 4.2.13 on 2026-04-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0010_categoria_model_and_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='ecommerce.producto'),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to=settings.AUTH_USER_MODEL),
        ),
    ]
