--
-- PostgreSQL database dump
--

\restrict c0LvLKAbixGx8DweVpl2gkNBGauvloZUWmBdEyCXxdXhVB1gNSCcMEsiA1Nva61

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO chocolate_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: chocolate_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO chocolate_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: chocolate_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO chocolate_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: chocolate_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO chocolate_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO chocolate_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: chocolate_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: chocolate_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO chocolate_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: chocolate_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO chocolate_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: chocolate_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO chocolate_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: chocolate_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO chocolate_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: chocolate_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO chocolate_user;

--
-- Name: ecommerce_carrito; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.ecommerce_carrito (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    usuario_id integer NOT NULL
);


ALTER TABLE public.ecommerce_carrito OWNER TO chocolate_user;

--
-- Name: ecommerce_categoria; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.ecommerce_categoria (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.ecommerce_categoria OWNER TO chocolate_user;

--
-- Name: ecommerce_categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: chocolate_user
--

ALTER TABLE public.ecommerce_categoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecommerce_categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecommerce_detallepedido; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.ecommerce_detallepedido (
    id uuid NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario numeric(10,2) NOT NULL,
    pedido_id uuid NOT NULL,
    producto_id uuid NOT NULL,
    CONSTRAINT ecommerce_detallepedido_cantidad_check CHECK ((cantidad >= 0))
);


ALTER TABLE public.ecommerce_detallepedido OWNER TO chocolate_user;

--
-- Name: ecommerce_envio; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.ecommerce_envio (
    id uuid NOT NULL,
    direccion_entrega character varying(255) NOT NULL,
    fecha_entrega date,
    numero_guia character varying(80) NOT NULL,
    estado character varying(20) NOT NULL,
    pedido_id uuid NOT NULL
);


ALTER TABLE public.ecommerce_envio OWNER TO chocolate_user;

--
-- Name: ecommerce_itemcarrito; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.ecommerce_itemcarrito (
    id uuid NOT NULL,
    cantidad integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    carrito_id uuid NOT NULL,
    producto_id uuid NOT NULL,
    CONSTRAINT ecommerce_itemcarrito_cantidad_check CHECK ((cantidad >= 0))
);


ALTER TABLE public.ecommerce_itemcarrito OWNER TO chocolate_user;

--
-- Name: ecommerce_pedido; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.ecommerce_pedido (
    id uuid NOT NULL,
    fecha timestamp with time zone NOT NULL,
    estado character varying(20) NOT NULL,
    total numeric(12,2) NOT NULL,
    usuario_id integer NOT NULL,
    factura_pdf character varying(100)
);


ALTER TABLE public.ecommerce_pedido OWNER TO chocolate_user;

--
-- Name: ecommerce_perfilusuario; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.ecommerce_perfilusuario (
    id bigint NOT NULL,
    rol character varying(10) NOT NULL,
    nombre_tienda character varying(200) NOT NULL,
    telefono character varying(20) NOT NULL,
    usuario_id integer NOT NULL,
    direccion character varying(255) NOT NULL,
    nombre character varying(200) NOT NULL
);


ALTER TABLE public.ecommerce_perfilusuario OWNER TO chocolate_user;

--
-- Name: ecommerce_perfilusuario_id_seq; Type: SEQUENCE; Schema: public; Owner: chocolate_user
--

ALTER TABLE public.ecommerce_perfilusuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecommerce_perfilusuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecommerce_producto; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.ecommerce_producto (
    id uuid NOT NULL,
    nombre character varying(150) NOT NULL,
    descripcion text NOT NULL,
    precio numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    marca character varying(120) NOT NULL,
    imagen character varying(100),
    activo boolean NOT NULL,
    tienda_id integer,
    categoria_id bigint,
    CONSTRAINT ecommerce_producto_stock_check CHECK ((stock >= 0))
);


ALTER TABLE public.ecommerce_producto OWNER TO chocolate_user;

--
-- Name: ecommerce_reseña; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public."ecommerce_reseña" (
    id uuid NOT NULL,
    calificacion smallint NOT NULL,
    comentario text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    producto_id uuid NOT NULL,
    usuario_id integer NOT NULL,
    CONSTRAINT "ecommerce_reseña_calificacion_check" CHECK ((calificacion >= 0))
);


ALTER TABLE public."ecommerce_reseña" OWNER TO chocolate_user;

--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO chocolate_user;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: chocolate_user
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: chocolate_user
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id integer,
    jti character varying(255) NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO chocolate_user;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: chocolate_user
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add blacklisted token	7	add_blacklistedtoken
26	Can change blacklisted token	7	change_blacklistedtoken
27	Can delete blacklisted token	7	delete_blacklistedtoken
28	Can view blacklisted token	7	view_blacklistedtoken
29	Can add outstanding token	8	add_outstandingtoken
30	Can change outstanding token	8	change_outstandingtoken
31	Can delete outstanding token	8	delete_outstandingtoken
32	Can view outstanding token	8	view_outstandingtoken
33	Can add producto	9	add_producto
34	Can change producto	9	change_producto
35	Can delete producto	9	delete_producto
36	Can view producto	9	view_producto
37	Can add carrito	10	add_carrito
38	Can change carrito	10	change_carrito
39	Can delete carrito	10	delete_carrito
40	Can view carrito	10	view_carrito
41	Can add item carrito	11	add_itemcarrito
42	Can change item carrito	11	change_itemcarrito
43	Can delete item carrito	11	delete_itemcarrito
44	Can view item carrito	11	view_itemcarrito
45	Can add pedido	12	add_pedido
46	Can change pedido	12	change_pedido
47	Can delete pedido	12	delete_pedido
48	Can view pedido	12	view_pedido
49	Can add detalle pedido	13	add_detallepedido
50	Can change detalle pedido	13	change_detallepedido
51	Can delete detalle pedido	13	delete_detallepedido
52	Can view detalle pedido	13	view_detallepedido
53	Can add perfil usuario	14	add_perfilusuario
54	Can change perfil usuario	14	change_perfilusuario
55	Can delete perfil usuario	14	delete_perfilusuario
56	Can view perfil usuario	14	view_perfilusuario
57	Can add envio	15	add_envio
58	Can change envio	15	change_envio
59	Can delete envio	15	delete_envio
60	Can view envio	15	view_envio
61	Can add reseña	16	add_reseña
62	Can change reseña	16	change_reseña
63	Can delete reseña	16	delete_reseña
64	Can view reseña	16	view_reseña
65	Can add categoria	17	add_categoria
66	Can change categoria	17	change_categoria
67	Can delete categoria	17	delete_categoria
68	Can view categoria	17	view_categoria
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$600000$5LpgSiDMCfpsIgnYQJTeow$pn06wtH2xBUcXVWGRf6BVnSyUKAsEsEuaW9hHj/sUXw=	\N	f	Emilton@hotmail.com	Emilton	Mena	Emilton@hotmail.com	f	t	2026-03-25 01:26:49.671432+00
2	pbkdf2_sha256$600000$CR8X6srJdnMpTgZ2DUEKXw$XXxJzMRoC7TmNc9aKO1I2g2eRo34vcdzObLcpoK1mOI=	\N	f	Emilton1@hotmail.com	Emilton	Mena	Emilton1@hotmail.com	f	t	2026-03-25 01:27:42.874304+00
3	pbkdf2_sha256$600000$KQyUHp4JvIZTB5yQRAz594$WDOrcaqZwapagfTxUYNvePR7vRSca4L5tn64yzIdQzE=	\N	f	wealth@hotmail.com	Karen	Sevillano	wealth@hotmail.com	f	t	2026-03-25 02:39:28.035685+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	token_blacklist	blacklistedtoken
8	token_blacklist	outstandingtoken
9	ecommerce	producto
10	ecommerce	carrito
11	ecommerce	itemcarrito
12	ecommerce	pedido
13	ecommerce	detallepedido
14	ecommerce	perfilusuario
15	ecommerce	envio
16	ecommerce	reseña
17	ecommerce	categoria
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-03-25 01:05:22.59051+00
2	auth	0001_initial	2026-03-25 01:05:22.657764+00
3	admin	0001_initial	2026-03-25 01:05:22.675955+00
4	admin	0002_logentry_remove_auto_add	2026-03-25 01:05:22.682531+00
5	admin	0003_logentry_add_action_flag_choices	2026-03-25 01:05:22.687865+00
6	contenttypes	0002_remove_content_type_name	2026-03-25 01:05:22.698649+00
7	auth	0002_alter_permission_name_max_length	2026-03-25 01:05:22.705814+00
8	auth	0003_alter_user_email_max_length	2026-03-25 01:05:22.712102+00
9	auth	0004_alter_user_username_opts	2026-03-25 01:05:22.717744+00
10	auth	0005_alter_user_last_login_null	2026-03-25 01:05:22.725408+00
11	auth	0006_require_contenttypes_0002	2026-03-25 01:05:22.728328+00
12	auth	0007_alter_validators_add_error_messages	2026-03-25 01:05:22.734395+00
13	auth	0008_alter_user_username_max_length	2026-03-25 01:05:22.747516+00
14	auth	0009_alter_user_last_name_max_length	2026-03-25 01:05:22.754117+00
15	auth	0010_alter_group_name_max_length	2026-03-25 01:05:22.761954+00
16	auth	0011_update_proxy_permissions	2026-03-25 01:05:22.767336+00
17	auth	0012_alter_user_first_name_max_length	2026-03-25 01:05:22.77326+00
18	ecommerce	0001_initial	2026-03-25 01:05:22.783568+00
19	ecommerce	0002_carrito_carritoitem	2026-03-25 01:05:22.815939+00
20	ecommerce	0003_itemcarrito_delete_carritoitem	2026-03-25 01:05:22.840865+00
21	ecommerce	0004_pedido_detallepedido	2026-03-25 01:05:22.871848+00
22	ecommerce	0005_producto_categoria_producto_tienda_and_more	2026-03-25 01:05:22.907916+00
23	ecommerce	0006_pedido_factura_pdf	2026-03-25 01:05:22.918398+00
24	ecommerce	0007_perfilusuario_nombre_perfilusuario_direccion_and_envio	2026-03-25 01:05:22.949227+00
25	ecommerce	0006_reseña	2026-03-25 01:05:22.975289+00
26	ecommerce	0008_merge_20260325_0105	2026-03-25 01:05:22.978192+00
27	sessions	0001_initial	2026-03-25 01:05:22.992133+00
28	token_blacklist	0001_initial	2026-03-25 01:05:23.032166+00
29	token_blacklist	0002_outstandingtoken_jti_hex	2026-03-25 01:05:23.042694+00
30	token_blacklist	0003_auto_20171017_2007	2026-03-25 01:05:23.056372+00
31	token_blacklist	0004_auto_20171017_2013	2026-03-25 01:05:23.072866+00
32	token_blacklist	0005_remove_outstandingtoken_jti	2026-03-25 01:05:23.086827+00
33	token_blacklist	0006_auto_20171017_2113	2026-03-25 01:05:23.098055+00
34	token_blacklist	0007_auto_20171017_2214	2026-03-25 01:05:23.137719+00
35	token_blacklist	0008_migrate_to_bigautofield	2026-03-25 01:05:23.191064+00
36	token_blacklist	0010_fix_migrate_to_bigautofield	2026-03-25 01:05:23.208369+00
37	token_blacklist	0011_linearizes_history	2026-03-25 01:05:23.212541+00
38	token_blacklist	0012_alter_outstandingtoken_user	2026-03-25 01:05:23.224744+00
39	ecommerce	0009_resena_rating_and_producto_indexes	2026-04-26 02:26:33.511063+00
40	ecommerce	0010_categoria_model_and_fk	2026-04-26 02:26:38.585825+00
41	ecommerce	0011_alter_reseña_producto_alter_reseña_usuario	2026-04-26 02:26:38.606903+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: ecommerce_carrito; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.ecommerce_carrito (id, created_at, updated_at, usuario_id) FROM stdin;
\.


--
-- Data for Name: ecommerce_categoria; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.ecommerce_categoria (id, nombre) FROM stdin;
1	Otros
2	Protector solar
3	Contorno de ojos
4	Limpiadores
5	Cremas
6	Tónicos
7	Exfoliantes
8	Máscaras
9	Serums
\.


--
-- Data for Name: ecommerce_detallepedido; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.ecommerce_detallepedido (id, cantidad, precio_unitario, pedido_id, producto_id) FROM stdin;
db87028e-1e6b-498c-9124-0f4263ac4f6b	1	3.00	3f0695ad-2c4e-4a77-b87f-e2f27210e1ab	fd56bff6-f1a4-4503-99d5-317ddbb3ce80
c23fd640-15a5-4abe-b7c2-46da2695ff41	1	89000.00	3f0695ad-2c4e-4a77-b87f-e2f27210e1ab	25844b32-188a-4384-89cd-46e189285c44
58d32aba-881c-44ff-a9ce-212bcb35f72d	1	160000.00	3f0695ad-2c4e-4a77-b87f-e2f27210e1ab	1c520bd0-a36d-42a9-8380-cbbc8f20166e
bf70e906-d0fd-49e6-a566-fec843e9af7c	1	3.00	20ae2146-fd64-4241-979a-436b49862cc8	fd56bff6-f1a4-4503-99d5-317ddbb3ce80
10d76ed8-53a5-483a-b57e-7e13e5d7e638	1	3.00	f4201598-5262-4a20-b9ab-fab261ba7bda	fd56bff6-f1a4-4503-99d5-317ddbb3ce80
83e060fc-7f6d-4cbe-a480-4d7e3aaa789a	1	89.00	f4201598-5262-4a20-b9ab-fab261ba7bda	25844b32-188a-4384-89cd-46e189285c44
c51699fd-a2a0-4a7d-95c6-67678bf91a33	1	3.00	69fa7a2d-f84e-4ace-9766-75ff5b61e43a	fd56bff6-f1a4-4503-99d5-317ddbb3ce80
732b98b8-b35f-4a7f-b0c2-613553753961	1	3.00	62b24c45-b02f-415d-a7d9-6dbdfb81117b	fd56bff6-f1a4-4503-99d5-317ddbb3ce80
87dca15d-71e6-4628-a0f6-d218a033cfa1	1	89.00	62b24c45-b02f-415d-a7d9-6dbdfb81117b	25844b32-188a-4384-89cd-46e189285c44
\.


--
-- Data for Name: ecommerce_envio; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.ecommerce_envio (id, direccion_entrega, fecha_entrega, numero_guia, estado, pedido_id) FROM stdin;
b19c4f49-49bb-46c2-b00c-11b5e2ea39c3	Cl. 63 Sur #43A-11, Alto Las Flores, Sabaneta, envigado	\N		entregado	3f0695ad-2c4e-4a77-b87f-e2f27210e1ab
97a145f1-35e3-44d8-8f02-e5a38583652e	Carrera 49 #7 sur 50, El Poblado, Medellín, Antioquia, envigado	\N		entregado	20ae2146-fd64-4241-979a-436b49862cc8
709b41fb-a681-48f3-b253-ab632e525ee7	Carrera 49 #7 sur 50, El Poblado, Medellín, Antioquia, envigado	\N		entregado	f4201598-5262-4a20-b9ab-fab261ba7bda
0d271bd3-6fb3-4772-beff-1b40185b4d97	Cl. 63 Sur #43A-11, Alto Las Flores, Sabaneta, Sabaneta	\N		pendiente	69fa7a2d-f84e-4ace-9766-75ff5b61e43a
0407ca8d-d97a-44e2-9672-46075ce5f4e0	Cl. 63 Sur #43A-11, Alto Las Flores, Sabaneta, Sabaneta	\N		pendiente	62b24c45-b02f-415d-a7d9-6dbdfb81117b
\.


--
-- Data for Name: ecommerce_itemcarrito; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.ecommerce_itemcarrito (id, cantidad, created_at, updated_at, carrito_id, producto_id) FROM stdin;
\.


--
-- Data for Name: ecommerce_pedido; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.ecommerce_pedido (id, fecha, estado, total, usuario_id, factura_pdf) FROM stdin;
3f0695ad-2c4e-4a77-b87f-e2f27210e1ab	2026-03-25 04:12:01.022046+00	entregado	249003.00	1	invoices/factura-3f0695ad-2c4e-4a77-b87f-e2f27210e1ab.pdf
20ae2146-fd64-4241-979a-436b49862cc8	2026-03-25 04:14:02.809251+00	entregado	3.00	1	invoices/factura-20ae2146-fd64-4241-979a-436b49862cc8.pdf
f4201598-5262-4a20-b9ab-fab261ba7bda	2026-03-25 11:25:00.428232+00	entregado	92.00	1	invoices/factura-f4201598-5262-4a20-b9ab-fab261ba7bda.pdf
69fa7a2d-f84e-4ace-9766-75ff5b61e43a	2026-04-26 02:28:24.738814+00	confirmado	3.00	1	invoices/factura-69fa7a2d-f84e-4ace-9766-75ff5b61e43a.pdf
62b24c45-b02f-415d-a7d9-6dbdfb81117b	2026-04-26 03:19:08.466217+00	confirmado	92.00	1	invoices/factura-62b24c45-b02f-415d-a7d9-6dbdfb81117b.pdf
\.


--
-- Data for Name: ecommerce_perfilusuario; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.ecommerce_perfilusuario (id, rol, nombre_tienda, telefono, usuario_id, direccion, nombre) FROM stdin;
2	tienda	RosaArte	+573148765432	2		Emilton Mena
3	tienda	Rhore	3254676484846	3		Karen Sevillano
1	cliente		3203987425	1	Cl. 63 Sur #43A-11, Alto Las Flores, Sabaneta, Sabaneta	Admin
\.


--
-- Data for Name: ecommerce_producto; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.ecommerce_producto (id, nombre, descripcion, precio, stock, marca, imagen, activo, tienda_id, categoria_id) FROM stdin;
90527265-3439-49d2-8e11-9764b420b6b4	Crema Facial de Retinol	Crema Facial de Retinol antiarrugas antienvejecimiento hidratante ácido hialurónico vitamina C crema Facial cuidado de la piel cremas blanqueadoras faciales	6.98	100	CLAFACE	products/1.png	t	2	5
d2d71f6a-e2ea-42e2-bafc-55643358e927	Contorno de ojos	Crema de ojos hidratante para ojeras e hinchazón.\r\nLa delicada piel alrededor de los ojos puede ser propensa a sufrir hinchazón, ojeras y otros signos visibles de fatiga. Agregar una crema humectante para los ojos a su rutina diaria de cuidado de la piel puede ayudar a hidratar, iluminar y suavizar el área debajo de los ojos.	500.00	50	Cerave	products/IMG_0437.jpeg	t	2	\N
4d73f455-9510-4094-8307-318a5e2851c1	Milky bifásico	Milky Rose, desmaquillante bifásico formulado especialmente para cuidar la delicada piel del rostro. Perfecto para desmaquillar cara, ojos y labios. H	7.00	30	Montoc	products/IMG_0440.jpeg	t	2	4
fd56bff6-f1a4-4503-99d5-317ddbb3ce80	Agua micelar	NIVEA Agua Micelar Regeneradora para pieles cansadas y sensibles contiene un 5% de Sérum con Pantenol y Escualeno y elimina eficazmente el maquillaje resistente al agua, las impurezas y la suciedad con unos pocos toques.	3.00	45	Nivea	products/IMG_0438.jpeg	t	2	4
46b338a0-7f5e-4a03-b78f-d280ef4341bd	Protector solar	El protector solar en barra de Tocobo brinda una potente defensa contra los daños causados por los rayos UVA y UVB. Además, está enriquecido con extractos naturales como de algodón y aloe vera que aportan propiedades antioxidantes y calmantes para proteger la piel y combatir los efectos negativos del sol, promoviendo una piel saludable y radiante.	20.00	48	Harumi	products/IMG_0441.jpeg	t	2	5
e0084fa2-a4b9-495f-aff3-e19b4b0dd631	Contorno de ojos	Descubre este gel que contiene una poderosa mezcla de Vitamina C encapsulada y Péptidos, todo lo que necesitas para una mirada más firme y brillante! Su fórmula también incluye cafeína, que ayuda a desinflamar la zona y ceramidas que protegen la barrera cutánea y mantiene la hidratación, mientras aporta firmeza y elasticidad.	12.00	67	Blusa - bar	products/IMG_0442.jpeg	t	2	5
2e03f29f-0df2-4141-a73b-ebd43953f214	glazing milk	Paso esencial: emulsión nutritiva tipo leche que hidrata, ilumina y fortalece la barrera cutánea.	15.00	60	Rhode	products/Captura_de_pantalla_2026-03-24_215356.png	t	3	6
43053054-1a8c-4057-a743-2b4bb7268037	Protector solar facial	protector solar facial tintado transparente UV es un protector solar sin aceite fabricado con óxido de zinc. Este protector solar facial teñido SPF 46 es ligero y ayuda a calmar y proteger los tipos de piel sensible propensos al acné, la rosácea y la decoloración.	4.95	25	EltaMD UV	products/Captura_de_pantalla_2026-03-24_220554.png	t	3	2
4764142f-4ef3-424d-9a7e-dd6102b42837	Ácido hialurónico 2% + B5 30ml	Ácido hialurónico 2% + B5 30ml - The Ordinary	690.00	1000	The ordinary	products/Hyaluronic-acid2_1024x1024.webp	t	2	6
9835ec4d-51e2-4479-a783-b7dfd0fb8b1c	Protector solar facial	con vitamina E revitalizante SPF 50, 50 ml,	34.99	15	COSRX	products/Captura_de_pantalla_2026-03-24_220320.png	t	3	2
10cd9698-2cb4-4aed-8f65-6c99d6a286d7	Crema Anti-Envejecimiento para Ojos	Tratamiento de ojos que reduce arrugas y bolsas, mejora firmeza y elasticidad con Pro-Xylane y ácido hialurónico. Piel más suave y joven.	20.00	20	L'Oreal Paris	products/Captura_de_pantalla_2026-03-24_220827.png	t	3	3
752e61a9-30f5-4c1c-b96d-8c25fdf1abfc	Crema hidratante con retinol	Crema de ojos con retinol que reduce ojeras e hinchazón mientras suaviza líneas finas y arrugas. Hidrata profundamente y ayuda a reafirmar el contorno para una mirada más firme, luminosa y rejuvenecida. Tamaño: 1.06 oz.	40.00	35	Doracome	products/Captura_de_pantalla_2026-03-24_221424.png	t	3	3
c5919447-b68f-41d2-bbca-d32e19948bd1	Jabón exfoliante en frío facial	Jabón facial 2 en 1 que limpia y exfolia suavemente, eliminando maquillaje e impurezas sin resecar. Formulado con aceites orgánicos y manteca de karité, deja la piel hidratada, suave y nutrida. Vegano. Tamaño: 100 g.	5.00	30	kokoro	products/Captura_de_pantalla_2026-03-24_222450.png	t	3	7
3ababc0b-c45c-44d4-8831-9150015da233	Prueba	hdhd	1.00	3	CeraVe	products/Captura_de_pantalla_2026-02-21_143440.png	t	2	2
e566a84a-0a58-44f9-979a-c58caf226fee	PM FACIAL MOISTURIZING LOTION - CERAVE	Crema humectante ligera de uso nocturno formulada con tres ceramidas esenciales que ayudan a fortalecer la barrera natural de la piel, ácido hialurónico hidratante y niacinamida que ayuda a calmar la piel.\r\n\r\nUsa la tecnología de entrega patentada MVE para proporcionar un flujo constante de hidratación durante la noche y ayuda a que la piel la retenga.	115.00	1100	CeraVe	products/pm-facial-moisturizing-lotion_1024x1024.webp	t	2	5
c1d397cd-5a86-401b-8541-9be15a67245e	Primer para rostro	El primer es un producto de maquillaje que sirve para darle a tu piel un aspecto aterciopelado, rellenando poros y matificando el rostro. También le da larga duración a tus looks y es ideal para todo tipo de piel.	13.00	60	Atenea	products/IMG_0439.jpeg	t	2	5
398dd805-c4d1-434e-970c-38c619b87335	Ácido Glicólico 7% Toning Solution	Una solución tonificante exfoliante con 7% de ácido glicólico, aminoácidos, aloe vera, ginseng y baya de Tasmania.\r\n\r\nEsta solución tonificante al 7% ofrece una exfoliación suave para mejorar la luminosidad de la piel y una claridad visible. La fórmula también mejora la apariencia de la textura de la piel con el uso continuo.\r\n\r\n\r\n--\r\nEsta fórmula contiene un derivado de la pimienta de Tasmania estudiado para ayudar a reducir la irritación asociada con el uso de ácido. La fórmula se ve reforzada con la inclusión de raíz de ginseng y aloe vera para obtener un brillo visible y beneficios calmantes.	135.00	900	The ordinary	products/GlycolicAcid7_ToningSolution-TheOrdinary_1024x1024.webp	t	2	6
5eae1657-77fb-45bf-a07e-edeb05f619d3	Niacinamida 10% + Zinc 1% 30ml - The Ordinary	Es un potente sérum con Vitamina B3 con el que ganarás tu lucha contra el acné. Con él, combatirás de raíz los síntomas más comunes previniendo los brotes acneicos, minimizando los poros y regulando la producción del sebo.Una fórmula de alta concentración de vitaminas y minerales con un 10% de Niacinamida pura y 1% de Zinc PCA.\r\n\r\nLa Niacinamida, entre sus múltiples maravillas, reduce los poros dilatados, elimina las marcas del acné, previene nuevos brotes e iguala el tono de la piel. Y el Zinc, tiene un poder antioxidante, porque regula las glándulas sebáceas y porque ayuda a cicatrizar el tejido.\r\n\r\nLa Niacinamida (vitamina B3) en una concentración del 10 está respaldada en la fórmula por la sal de zinc del ácido pirrolidona carboxílico para equilibrar los aspectos visibles de la actividad del sebo.	79.00	1000	The ordinary	products/Niacinamide_1024x1024.webp	t	2	6
5460b56e-6177-43ae-8ae0-3e6334a6776e	Glazing Milk Esencia Facial con Ceramidas (124 ml)	Descubre la esencia lechosa más icónica del momento. Rhode Glazing Milk es el paso esencial en tu rutina de skincare: una textura ligera y cremosa que prepara, hidrata y protege, dejándote ese efecto glow fresco y uniforme que tanto amamos en una sola aplicación.\r\n\r\nFormulada con ceramidas reparadoras, vitamina E antioxidante y un complejo mineral rico en magnesio, zinc y cobre, esta esencia fortalece visiblemente la barrera cutánea, reduce el enrojecimiento y deja la piel jugosa, luminosa y calmada durante todo el día.	245.00	675	Rhode	products/s2898419-main-zoom_1024x1024.webp	t	2	6
03678382-4136-4d5c-b7bf-94f0e51d3a1f	Mascarilla de arcilla	Experimente poros visiblemente minimizados y oleosidad reducida en solo 10 minutos! Nuestro minimizador de poros está clínicamente validado para brindar resultados inmediatos. Con solo una aplicación, puede reducir los poros, aclarar la zona T y disminuir la oleosidad para una tez más suave. Formulada con arcilla de caolín, carbonato de calcio y óxido de zinc, esta mascarilla que absorbe la grasa refina los poros grandes y combate la piel grasa, dejándole una tez más suave y refinada. Nuestro minimizador de poros se transforma en una pasta ligera cuando se mezcla con un algodón humedecido en agua, lo que facilita su aplicación para una máxima eficacia.	23.00	47	Cromatic	products/IMG_0443.jpeg	t	2	7
0736376b-f40c-42bc-8057-dfc43ab1cbd0	Mascarilla  hidratante matificante	¿ Necesitas matificar e hidratar tu piel grasa ? con revolucionaria tecnología en tejido ultrafino de origen vegetal, que actúa como una bomba de hidratación en tan solo 15 minutos. Esta mascarilla, que es equivalente a una botella de suero hidratante, esta enriquecida con ACIDO HIALURONICO y TE VERDE de origen natural, con accion masificante. Apta para pieles mixtas a grasas, incluso las sensibles.	3.00	78	Garnier	products/IMG_0444.jpeg	t	2	8
da70e82d-32a0-4757-ab7e-01a8c1935539	Tónico anti- imperfecciones	El Kit Cuidado Dual LB es tu solución integral para sentirte impecable y segura en todo momento. Este dúo profesional combina dos tratamientos especializados que trabajan en las áreas más importantes de tu cuidado personal: rostro y zona íntima.	21.00	34	Ibsas	products/IMG_0445.jpeg	t	2	6
6fa7d1a6-7ef4-4fde-99cd-ea22e6b8f304	Crema aclarante	Aplicar una o dos veces al día en las áreas afectadas (rodillas, codos, axilas, muslos, ingle) y áreas íntimas externas. El producto se puede usar directamente después de depilarse o afeitarse para ayudar a prevenir el enrojecimiento y las diferencias en el color de la piel. Solo uso externo.	6.00	50	Bioderma	products/IMG_0446.jpeg	t	2	5
227531a5-a270-4b7d-bad2-c4566564dbb9	Caffeine reset reinicio de cafeína	Mascarilla facial con cafeína que despierta la piel, reduce la hinchazón y deja el rostro más firme y fresco en minutos. Hidrata y aporta luminosidad duradera. Tamaño: 50 ml.	30.00	60	Rhode	products/Captura_de_pantalla_2026-03-24_215119.png	t	3	8
46e5e250-c766-40de-8cf4-c8d5326d62b4	The nourishing lip layer La capa nutritiva de labios	Peptide Lip Treatment in Strawberry Glaze has joined the rhode lineup forever. Originally launched in 2023, it was one of your favorite limited edition Peptide Lip Treatments that smells like a fresh strawberry glazed donut. Our nourishing formula hydrates and replenishes lips while leaving a glossy, high-shine finish. Size: 10ml / .3 fl oz.\r\n\r\nThe complete collection is now available in our improved formula. Same nourishing gloss you know and love, with a lasting smooth texture.\r\nEl tratamiento de labios con péptidos en Strawberry Glaze se ha unido para siempre a la gama de Rhode. Lanzado originalmente en 2023, era uno de tus tratamientos labiales de edición limitada favoritos que huele a un donut fresco glaseado con fresa. Nuestra fórmula nutritiva hidrata y repone los labios mientras deja un acabado brillante y de alto resplandor. Tamaño: 10ml / 0,3 fl oz. La colección completa ya está disponible en nuestra fórmula mejorada. El mismo brillo nutritivo que conoces y te encanta, con una textura suave y duradera	40.00	50	Rhode	products/Captura_de_pantalla_2026-03-24_214819.png	t	3	1
d1cb4273-77a8-4b6d-ab53-e32d75efe5b1	essential drip mini lip oil Aceite Labial Esencial Drip Mini	Brillo labial con color ligero, aroma irresistible y acabado ultra glossy. Hidrata como aceite sin sensación pegajosa.	10.00	160	Rem beauty	products/Captura_de_pantalla_2026-03-24_215839.png	t	3	1
aec20067-5e2f-4072-a748-01667c728b60	pineapple refresh refresco de piña	Limpiador diario bálsamo a espuma que elimina SPF y maquillaje sin resecar. Deja la piel limpia, suave e hidratada.	10.00	60	Rhode	products/Captura_de_pantalla_2026-03-24_215633.png	t	3	4
e07d6332-e730-4a92-8c5e-eb93d1de1bd4	Glazing Mist Hydrating Face Spray	Tu glow-to-go definitivo ✨\r\nUn spray facial ultrafino y de alto rendimiento que hidrata, refresca y deja la piel con ese acabado glazed característico de Rhode — luminoso, jugoso y saludable.\r\n\r\n Tipo de piel: Normal, seca, mixta y grasa\r\n Preocupaciones: Sequedad y opacidad\r\n Fórmula: Spray hidratante	215.00	874	Rhode	products/s2895977-main-zoom_1024x1024.webp	t	2	6
16117ee2-c85e-49ed-b6c4-2ef72daf79ba	CONTORNO DE OJOS CON AGUACATE	Qué es: Un contorno de ojos de aguacate que aporta un rápido chute de hidratación. Formulada con aceite de aguacate, betacaroteno y manteca de karité, esta cremosa fórmula es una favorita de nuestros consumidores\r\n\r\n¿Para qué es buena?\r\n\r\nHidrata suavemente la delicada zona del contorno de ojos\r\n\r\nFórmula muy concentrada que no migra a los ojos\r\n\r\nProbado por oftalmólogos y dermatólogos para garantizar su seguridad\r\n\r\nPara todos los tipos de piel, incluidas las pieles sensibles	28.00	520	THE KIEHL'S	products/s1988823-main-zoom_1024x1024.webp	t	2	3
8e8200d1-3c4c-42cc-873f-ac1c71eb8f4b	Mary & May	Sérum con 6 péptidos que mejora firmeza, reduce arrugas y aporta luminosidad. Fórmula segura con ingredientes EWG Green Grade.	12.00	30	kokoro	products/Captura_de_pantalla_2026-03-24_223330.png	t	3	9
cc934974-b1da-4379-880b-d6714bfa7cbc	Mini Glazed Skincare Essentials Kit	Descubre la rutina completa de Hailey Bieber en versión mini.\r\nUn set con los cuatro productos esenciales de Rhode, diseñados para lograr esa piel glazed, luminosa y saludable que amamos. 💧🤍\r\n\r\n🌿 Tipo de piel: Normal, seca, mixta y grasa.\r\n💫 Preocupaciones: Sequedad, opacidad y enrojecimiento.\r\n\r\nContiene:\r\n\r\n🧼 Pineapple Refresh Cleanser (40ml) — limpia suavemente mientras renueva la textura con enzimas de piña.\r\n\r\n🍼 Glazing Milk (65ml) — una loción ligera con ceramidas que hidrata y fortalece la barrera cutánea.\r\n\r\n💧 Peptide Glazing Fluid (15ml) — el suero icónico con niacinamida que deja la piel radiante y fresca.\r\n\r\n🪞 Barrier Restore Cream (30ml) — crema nutritiva con péptidos que suaviza y rellena visiblemente la piel.\r\n\r\n🌱 Vegano y libre de crueldad animal.\r\n\r\n💖 Por qué lo amarás:\r\nCada fórmula trabaja en sinergia para hidratar, calmar e iluminar tu piel desde el primer uso. Ideal para viajar o para probar la rutina más viral del momento.\r\n\r\n Resultados clínicos:\r\n 100% notó una limpieza profunda y sin resecar\r\n 97% vio su piel más luminosa\r\n 92% sintió hidratación instantánea\r\n 95% afirmó que su piel se veía más saludable	44.00	343	Rhode	products/s2898575-main-zoom_1024x1024.webp	t	2	1
dcd83555-a0d3-48c5-8a38-b3e2c8e610db	Cream for Rough & Bumpy Skin	Formulada con ácido salicílico y ácido láctico para exfoliar suavemente las células muertas y la piel irregular, además de ácido hialurónico hidratante y niacinamida calmante, nuestra crema sin perfume para pieles ásperas e irregulares ayuda a mejorar la textura general de la piel.\r\nIdeal para: Piel áspera e irregular\r\nAyuda con: Hidratación, exfoliación\r\nDetalles del Producto\r\n\r\nUna crema con ácido salicilico puede exfoliar, suavizar y aliviar la piel aspera, como la piel escamosa en la parte superior de los brazos y los muslos (y toda la piel que se sienta como “de gallina”). CeraVe SA Cream for Rough and Bumpy Skin está diseñada para mejorar la textura de la piel y suavizar la piel muy seca y áspera. Formulada con ácido salicílico y ácido lactico  para exfoliar suavemente las células muertas de la piel y la piel áspera, así como ácido hialurónico hidratante y niacinamida para aliviar la piel,nuestra crema sin fragancia para piel áspera ayuda a mejorar la textura general de la piel.\r\n\r\nLos ingredientes de SA Cream de CeraVe, que incluyen tres ceramidas esenciales, trabajan juntos para retener la hidratación y ayudar a mantener la barrera protectora de la piel. Además, la tecnología MVE libera continuamente ingredientes humectantes para una hidratación que dura todo el día. La hidratación duradera favorece la barrera protectora de la piel, mucho después de que haber terminado de aplicarla.	130.00	625	CeraVe	products/sa-cream-for-rough-and-bumpy-skin-with-badge-front-700x700-v1_1024x1024.webp	t	2	5
d878f3a2-2712-43c8-a094-fe3af520d56e	Collagen Niacinamide Jelly Cream – Medicube (50 ml)	La Collagen Niacinamide Jelly Cream de Medicube es una crema en textura gelatina transparente que combina lo mejor de la ciencia coreana con el lujo cosmético. Su fórmula avanzada hidrata, reafirma y suaviza la piel mientras mejora visiblemente el contorno facial y revela un efecto glow tipo “Korean Glass Skin” desde la primera semana de uso.\r\n\r\n🌿 Ingredientes estrella:\r\nColágeno hidrolizado liofilizado: de bajo peso molecular, mejora elasticidad y firmeza con absorción profunda.\r\n\r\nNiacinamida (Vitamina B3): refuerza la barrera cutánea, mejora textura y tono.\r\n\r\nEscualano vegetal: suaviza y evita la pérdida de hidratación.\r\n\r\nElastina hidrolizada: promueve una piel flexible y radiante.\r\n\r\n💧 Beneficios:\r\nAumenta la hidratación y el volumen de la piel\r\n\r\nMejora contornos faciales y reduce la flacidez\r\n\r\nAcabado luminoso, suave y tenso\r\n\r\nTextura gelatinosa y ligera, ideal para todo tipo de piel\r\n\r\nFórmula con pH equilibrado | Sin siliconas ni colorantes artificiales\r\n\r\n🕗 Modo de uso:\r\nAM: Aplícala después de tus sueros y antes del maquillaje. Masajea hasta absorción total.\r\nPM: Aplica una cantidad generosa después de tu limpieza facial, evitando el contorno de ojos y labios.	175.00	1200	Medicube	products/61leLgR06vL._SL1500_1024x1024.webp	t	2	5
1c520bd0-a36d-42a9-8380-cbbc8f20166e	CLEAN IT ZERO BANILA CO	¿Qué es? Clean it Zero 3-in-1 Cleansing Balm Original es un bálsamo limpiador hipoalergénico que se transforma de una textura sólida a un aceite suave cuando se aplica sobre la piel. Desarrollado para eliminar incluso el maquillaje resistente al agua y todas las impurezas de tu piel en un solo paso. La tecnología Zero Balance limpia profundamente sin dañar tu piel, dejándola hidratada y fresca.\r\n\r\nEste maravilloso bálsamo disuelve el maquillaje y el sebo facial endurecido, arrastrando las impurezas de la piel de una manera gentil y respetuosa con el PH de nuestra piel y su barrera protectora (manto ácido).	160.00	449	Banila Co	products/banilacocleanbalm_1024x1024.webp	t	2	4
25844b32-188a-4384-89cd-46e189285c44	CERAVE Facial Moisturizing Lotion PM	CeraVe PM Facial Moisturizer está formulada con niacinamida, ácido hialurónico y tres ceramidas esenciales y utiliza nuestra tecnología MVE para proporcionar un flujo constante de hidratación muy necesario durante toda la noche y ayudar a restaurar la barrera cutánea.\r\nIdeal para: Todo tipo de piel\r\nAyuda con: Hidratación	89.00	1497	CeraVe	products/cerave_pm-facial-moisturizing-lotion-3oz_front-700x875-v2_1024x1024.webp	t	2	5
\.


--
-- Data for Name: ecommerce_reseña; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public."ecommerce_reseña" (id, calificacion, comentario, created_at, producto_id, usuario_id) FROM stdin;
ca0a8403-9747-4913-a272-87cb8c10ec7c	5	Buen producto	2026-03-25 04:14:13.280205+00	fd56bff6-f1a4-4503-99d5-317ddbb3ce80	1
\.


--
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;
1	2026-03-25 01:27:08.12842+00	2
2	2026-03-25 01:35:45.629769+00	4
3	2026-03-25 04:12:16.169071+00	12
4	2026-03-25 04:12:37.79885+00	13
5	2026-03-25 04:14:19.344408+00	14
6	2026-03-25 04:14:38.8141+00	15
38	2026-03-25 11:11:58.285413+00	48
39	2026-03-25 11:12:05.825853+00	49
40	2026-03-25 11:22:56.984216+00	50
41	2026-03-25 11:25:12.550471+00	51
\.


--
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: chocolate_user
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;
1	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTAwNjgwOSwiaWF0IjoxNzc0NDAyMDA5LCJqdGkiOiJiZTk5MDU1NmM0NmQ0MDNmOWQxOTg4NmU2YTE5NTA5NCIsInVzZXJfaWQiOjF9.ZRPqODDNYHdG2qQA3SpQWc_TXujzkmSGjz3o7tOOl_o	2026-03-25 01:26:49.794755+00	2026-04-01 01:26:49+00	1	be990556c46d403f9d19886e6a195094
2	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTAwNjgwOSwiaWF0IjoxNzc0NDAyMDA5LCJqdGkiOiI4NWYxNWQxNzY3Yjc0MmFkYTIzNDAzMzUyZThiNmZjMCIsInVzZXJfaWQiOjF9.Y1tiGjUpRotf2knm4rVbjM9u4uLpKdky1rp_dnZhu-U	2026-03-25 01:26:49.942371+00	2026-04-01 01:26:49+00	1	85f15d1767b742ada23403352e8b6fc0
3	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTAwNjg2MiwiaWF0IjoxNzc0NDAyMDYyLCJqdGkiOiI5ZjdmOWU2MTg3YTg0ODViODk2NjQ2ZmY1YjQ5ZDk1MyIsInVzZXJfaWQiOjJ9.A05AQtpe3u2dg6bT6EIbZoFIPNotLlHtNkKoXWRLWAE	2026-03-25 01:27:42.988376+00	2026-04-01 01:27:42+00	2	9f7f9e6187a8485b896646ff5b49d953
4	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTAwNjg2MywiaWF0IjoxNzc0NDAyMDYzLCJqdGkiOiJmNTAzZGU0ZTRkMDA0YzdlYjRlNmFmZjc0NGJmNGEwZSIsInVzZXJfaWQiOjJ9.Ms0GUs2DJ-W9jZo90wH7nt9nFR_OHk8chTb-5V4Ka4s	2026-03-25 01:27:43.120735+00	2026-04-01 01:27:43+00	2	f503de4e4d004c7eb4e6aff744bf4a0e
5	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTAxMDExMCwiaWF0IjoxNzc0NDA1MzEwLCJqdGkiOiIxMzE2NjMyZGFmOGE0NWQ0OTU0OWMwY2Q3MWJjMDlmNyIsInVzZXJfaWQiOjJ9.0exzRUGWHXr5Wj-nXnGafn3A5e1iSAza3POFr_rwgr8	2026-03-25 02:21:50.370597+00	2026-04-01 02:21:50+00	2	1316632daf8a45d49549c0cd71bc09f7
6	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTAxMDQxOSwiaWF0IjoxNzc0NDA1NjE5LCJqdGkiOiJlZGFkNjZiZDMxMmQ0NjQzYmU1ZDU1NGE2OGY4NTg3MyIsInVzZXJfaWQiOjF9.VHJILVuhIBjBOZVuOzqDHeAGNQy8x_AaSXIMbMry4mI	2026-03-25 02:26:59.59999+00	2026-04-01 02:26:59+00	1	edad66bd312d4643be5d554a68f85873
7	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTAxMDQyNSwiaWF0IjoxNzc0NDA1NjI1LCJqdGkiOiJjMWViZTRkNjZkN2E0YWU0OTc0MjNkYWYxNzc0YTI1YyIsInVzZXJfaWQiOjJ9.eGUDgRSuLOjQkU6t35NZyrbNHwJE-rrVDmwl-IZC-5s	2026-03-25 02:27:05.120565+00	2026-04-01 02:27:05+00	2	c1ebe4d66d7a4ae497423daf1774a25c
8	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTAxMDc1NCwiaWF0IjoxNzc0NDA1OTU0LCJqdGkiOiIwYWFhMjFmYTI3OGI0YWVlODU5ZjQwMTZhMzJhY2Y0MCIsInVzZXJfaWQiOjJ9.U1TsawJbW5Jm8QzmoHD7h_cGuKDl-v0sgtXf3ZYLMaI	2026-03-25 02:32:34.075611+00	2026-04-01 02:32:34+00	2	0aaa21fa278b4aee859f4016a32acf40
9	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTAxMTE2OCwiaWF0IjoxNzc0NDA2MzY4LCJqdGkiOiI4YzdlN2Y3MmZmOWI0NmY5YTdlYzA3ZWQ0OTY5NWMxYiIsInVzZXJfaWQiOjN9.t3BjNvU5foT7UqJwCYrAdWaonnh-H9ytajCkVTLP-LU	2026-03-25 02:39:28.162612+00	2026-04-01 02:39:28+00	3	8c7e7f72ff9b46f9a7ec07ed49695c1b
10	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTAxMTE2OCwiaWF0IjoxNzc0NDA2MzY4LCJqdGkiOiIxMjBiOGVkZjg0MzQ0YTFiOWVmNWVlNjNmMWQ0ZTQ5OCIsInVzZXJfaWQiOjN9.srU4RHdzovF2tD1rfGPnaWPIT_CGa6_AqNrL5-9U2mg	2026-03-25 02:39:28.307568+00	2026-04-01 02:39:28+00	3	120b8edf84344a1b9ef5ee63f1d4e498
11	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTAxMTU5NSwiaWF0IjoxNzc0NDA2Nzk1LCJqdGkiOiJlZWYxOTM5OGVlMGI0ZjllYmI5MTlhYWI3NzA2N2EwZCIsInVzZXJfaWQiOjN9.zP6ZApg4TZV-2MhAA-tI9MleJZW4NthW5AkOwWcQCPY	2026-03-25 02:46:35.751942+00	2026-04-01 02:46:35+00	3	eef19398ee0b4f9ebb919aab77067a0d
12	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTAxNjY4NSwiaWF0IjoxNzc0NDExODg1LCJqdGkiOiIyNDJmNmNmMWQ1YzY0MTVhYjRmNDljYmQwZjgzZTEwMSIsInVzZXJfaWQiOjF9.3-s080dMoeaRlp9x-TjiF7meO_rkN6oDMObR0qA1q8Q	2026-03-25 04:11:25.392275+00	2026-04-01 04:11:25+00	1	242f6cf1d5c6415ab4f49cbd0f83e101
13	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTAxNjc0MywiaWF0IjoxNzc0NDExOTQzLCJqdGkiOiJkYjAzODE0Y2JhZGQ0NjRkYjEzNDQ5NTQ3NGM1YTdiZSIsInVzZXJfaWQiOjJ9.OI7bj3X7cPs9M6wd4lemaECdYzkfU5Yu72VnJSq8xEI	2026-03-25 04:12:23.962431+00	2026-04-01 04:12:23+00	2	db03814cbadd464db134495474c5a7be
14	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTAxNjc3MiwiaWF0IjoxNzc0NDExOTcyLCJqdGkiOiI4MjllM2UzNTUzNTE0NmE1ODkwZWI5Y2I1MWJkYjAxNiIsInVzZXJfaWQiOjF9.VOE9upKn9f7QOB6z3JjmGpGcFSMkMHioQOSvQJg5-LY	2026-03-25 04:12:52.327256+00	2026-04-01 04:12:52+00	1	829e3e35535146a5890eb9cb51bdb016
15	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTAxNjg2NSwiaWF0IjoxNzc0NDEyMDY1LCJqdGkiOiI0NWRlMzVmYWE1NDg0OGRiYWIyNWQ0NGQwZjQ1YTMyYSIsInVzZXJfaWQiOjJ9.ymnnfJJgD_bzqh06IJDds3ZyYeSzYVYfW1L-JzNX9Wc	2026-03-25 04:14:25.975991+00	2026-04-01 04:14:25+00	2	45de35faa54848dbab25d44d0f45a32a
16	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTAxNjg4NSwiaWF0IjoxNzc0NDEyMDg1LCJqdGkiOiJmY2JlMmUxMTE1OTA0ZDgxODFiMGRkOWQ1MmNlYmYzZCIsInVzZXJfaWQiOjF9.5ervIT2FtnSJ1iTjxyyrWU2Ebj8oufN9_SPRshNx44o	2026-03-25 04:14:45.396835+00	2026-04-01 04:14:45+00	1	fcbe2e1115904d8181b0dd9d52cebf3d
48	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTA0MTM2NSwiaWF0IjoxNzc0NDM2NTY1LCJqdGkiOiIzZGZlZWExZDQ1YTc0NDJhYjMzOWRjZTA3OTU5YWI3MiIsInVzZXJfaWQiOjJ9.uI4oVg7ngTDgTeRI2V3zRBrPvKWrGAJnMRpWX-awvbU	2026-03-25 11:02:45.569703+00	2026-04-01 11:02:45+00	2	3dfeea1d45a7442ab339dce07959ab72
49	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTA0MTkyMSwiaWF0IjoxNzc0NDM3MTIxLCJqdGkiOiI4YWEwYTYwN2IyYTE0ZTRkOTBiZjFjYmE2NDRmNDkzMSIsInVzZXJfaWQiOjJ9.Ni5fvfEdrPOV5ewVqLnOjcZJNoHbe4gO-lr5FExsM6U	2026-03-25 11:12:01.077435+00	2026-04-01 11:12:01+00	2	8aa0a607b2a14e4d90bf1cba644f4931
50	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTA0MTkzNSwiaWF0IjoxNzc0NDM3MTM1LCJqdGkiOiIwYjIyYjhiNjAzNWU0NDUzYjIwODM3OGI4YTljZDAxMSIsInVzZXJfaWQiOjF9.584eNJGNtQfn11_5ckev_f75alwPF9OqvTf6CoDOYcY	2026-03-25 11:12:15.048913+00	2026-04-01 11:12:15+00	1	0b22b8b6035e4453b208378b8a9cd011
51	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTA0MjYzMCwiaWF0IjoxNzc0NDM3ODMwLCJqdGkiOiI1Yjk1NDJmODg5Yzc0ZmEyOThkYTNlNmE4NzBmMTI5YyIsInVzZXJfaWQiOjF9.DbZi42syi9gTYfAIxG_vOL4ArcFQ0MQHdX1pcGTy8jg	2026-03-25 11:23:50.762914+00	2026-04-01 11:23:50+00	1	5b9542f889c74fa298da3e6a870f129c
52	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTA0MjcyNCwiaWF0IjoxNzc0NDM3OTI0LCJqdGkiOiJlNGNiNzcwZmNjMWY0MGM1YjBiODE2ZTYxNWI1MDgyYiIsInVzZXJfaWQiOjJ9.WBD3IfVeZMCVHUDZlWbSyArnI6zZ2E-i6zYneIcdj_Q	2026-03-25 11:25:24.481782+00	2026-04-01 11:25:24+00	2	e4cb770fcc1f40c5b0b816e615b5082b
53	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3Nzc3NTIxOSwiaWF0IjoxNzc3MTcwNDE5LCJqdGkiOiJiNDAwOTk2NjFiZDE0NzFhOWM4NDI4Y2U0ZmU3NjE0ZiIsInVzZXJfaWQiOjF9.et0_NOaG6QayyangH-onUHodDH8_mjWKUvaPUwMZTd0	2026-04-26 02:26:59.062018+00	2026-05-03 02:26:59+00	1	b40099661bd1471a9c8428ce4fe7614f
54	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3Nzc3NTI1MCwiaWF0IjoxNzc3MTcwNDUwLCJqdGkiOiIxNGExNGQzYjAzYzc0MDkxYjYxMzBkMWQ4Y2E2MWEzNSIsInVzZXJfaWQiOjF9.1My2BMxwGtBuZPq9cr1iSojOISIkOZnsvVxaELucMJI	2026-04-26 02:27:30.774223+00	2026-05-03 02:27:30+00	1	14a14d3b03c74091b6130d1d8ca61a35
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: chocolate_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: chocolate_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: chocolate_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 68, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: chocolate_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: chocolate_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 3, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: chocolate_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: chocolate_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: chocolate_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: chocolate_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 41, true);


--
-- Name: ecommerce_categoria_id_seq; Type: SEQUENCE SET; Schema: public; Owner: chocolate_user
--

SELECT pg_catalog.setval('public.ecommerce_categoria_id_seq', 9, true);


--
-- Name: ecommerce_perfilusuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: chocolate_user
--

SELECT pg_catalog.setval('public.ecommerce_perfilusuario_id_seq', 3, true);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: chocolate_user
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 41, true);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: chocolate_user
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 54, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: ecommerce_carrito ecommerce_carrito_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_carrito
    ADD CONSTRAINT ecommerce_carrito_pkey PRIMARY KEY (id);


--
-- Name: ecommerce_carrito ecommerce_carrito_usuario_id_key; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_carrito
    ADD CONSTRAINT ecommerce_carrito_usuario_id_key UNIQUE (usuario_id);


--
-- Name: ecommerce_categoria ecommerce_categoria_nombre_key; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_categoria
    ADD CONSTRAINT ecommerce_categoria_nombre_key UNIQUE (nombre);


--
-- Name: ecommerce_categoria ecommerce_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_categoria
    ADD CONSTRAINT ecommerce_categoria_pkey PRIMARY KEY (id);


--
-- Name: ecommerce_detallepedido ecommerce_detallepedido_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_detallepedido
    ADD CONSTRAINT ecommerce_detallepedido_pkey PRIMARY KEY (id);


--
-- Name: ecommerce_envio ecommerce_envio_pedido_id_key; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_envio
    ADD CONSTRAINT ecommerce_envio_pedido_id_key UNIQUE (pedido_id);


--
-- Name: ecommerce_envio ecommerce_envio_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_envio
    ADD CONSTRAINT ecommerce_envio_pkey PRIMARY KEY (id);


--
-- Name: ecommerce_itemcarrito ecommerce_itemcarrito_carrito_id_producto_id_aecc64af_uniq; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_itemcarrito
    ADD CONSTRAINT ecommerce_itemcarrito_carrito_id_producto_id_aecc64af_uniq UNIQUE (carrito_id, producto_id);


--
-- Name: ecommerce_itemcarrito ecommerce_itemcarrito_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_itemcarrito
    ADD CONSTRAINT ecommerce_itemcarrito_pkey PRIMARY KEY (id);


--
-- Name: ecommerce_pedido ecommerce_pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_pedido
    ADD CONSTRAINT ecommerce_pedido_pkey PRIMARY KEY (id);


--
-- Name: ecommerce_perfilusuario ecommerce_perfilusuario_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_perfilusuario
    ADD CONSTRAINT ecommerce_perfilusuario_pkey PRIMARY KEY (id);


--
-- Name: ecommerce_perfilusuario ecommerce_perfilusuario_usuario_id_key; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_perfilusuario
    ADD CONSTRAINT ecommerce_perfilusuario_usuario_id_key UNIQUE (usuario_id);


--
-- Name: ecommerce_producto ecommerce_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_producto
    ADD CONSTRAINT ecommerce_producto_pkey PRIMARY KEY (id);


--
-- Name: ecommerce_reseña ecommerce_reseña_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public."ecommerce_reseña"
    ADD CONSTRAINT "ecommerce_reseña_pkey" PRIMARY KEY (id);


--
-- Name: ecommerce_reseña ecommerce_reseña_producto_id_usuario_id_1ee3f383_uniq; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public."ecommerce_reseña"
    ADD CONSTRAINT "ecommerce_reseña_producto_id_usuario_id_1ee3f383_uniq" UNIQUE (producto_id, usuario_id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: ecommerce_categoria_nombre_fa484740_like; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX ecommerce_categoria_nombre_fa484740_like ON public.ecommerce_categoria USING btree (nombre varchar_pattern_ops);


--
-- Name: ecommerce_detallepedido_pedido_id_2b27e44b; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX ecommerce_detallepedido_pedido_id_2b27e44b ON public.ecommerce_detallepedido USING btree (pedido_id);


--
-- Name: ecommerce_detallepedido_producto_id_badd7a2f; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX ecommerce_detallepedido_producto_id_badd7a2f ON public.ecommerce_detallepedido USING btree (producto_id);


--
-- Name: ecommerce_itemcarrito_carrito_id_60c4faf8; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX ecommerce_itemcarrito_carrito_id_60c4faf8 ON public.ecommerce_itemcarrito USING btree (carrito_id);


--
-- Name: ecommerce_itemcarrito_producto_id_96ba4caa; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX ecommerce_itemcarrito_producto_id_96ba4caa ON public.ecommerce_itemcarrito USING btree (producto_id);


--
-- Name: ecommerce_p_catego_12f799_idx; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX ecommerce_p_catego_12f799_idx ON public.ecommerce_producto USING btree (categoria_id, activo);


--
-- Name: ecommerce_pedido_usuario_id_bae8e245; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX ecommerce_pedido_usuario_id_bae8e245 ON public.ecommerce_pedido USING btree (usuario_id);


--
-- Name: ecommerce_producto_categoria_id_8e5a1cdf; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX ecommerce_producto_categoria_id_8e5a1cdf ON public.ecommerce_producto USING btree (categoria_id);


--
-- Name: ecommerce_producto_tienda_id_49e5a762; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX ecommerce_producto_tienda_id_49e5a762 ON public.ecommerce_producto USING btree (tienda_id);


--
-- Name: ecommerce_reseña_producto_id_e3eb4cd3; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX "ecommerce_reseña_producto_id_e3eb4cd3" ON public."ecommerce_reseña" USING btree (producto_id);


--
-- Name: ecommerce_reseña_usuario_id_87c75aa3; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX "ecommerce_reseña_usuario_id_87c75aa3" ON public."ecommerce_reseña" USING btree (usuario_id);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: chocolate_user
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecommerce_carrito ecommerce_carrito_usuario_id_c03243af_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_carrito
    ADD CONSTRAINT ecommerce_carrito_usuario_id_c03243af_fk_auth_user_id FOREIGN KEY (usuario_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecommerce_detallepedido ecommerce_detalleped_pedido_id_2b27e44b_fk_ecommerce; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_detallepedido
    ADD CONSTRAINT ecommerce_detalleped_pedido_id_2b27e44b_fk_ecommerce FOREIGN KEY (pedido_id) REFERENCES public.ecommerce_pedido(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecommerce_detallepedido ecommerce_detalleped_producto_id_badd7a2f_fk_ecommerce; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_detallepedido
    ADD CONSTRAINT ecommerce_detalleped_producto_id_badd7a2f_fk_ecommerce FOREIGN KEY (producto_id) REFERENCES public.ecommerce_producto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecommerce_envio ecommerce_envio_pedido_id_9115b27c_fk_ecommerce_pedido_id; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_envio
    ADD CONSTRAINT ecommerce_envio_pedido_id_9115b27c_fk_ecommerce_pedido_id FOREIGN KEY (pedido_id) REFERENCES public.ecommerce_pedido(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecommerce_itemcarrito ecommerce_itemcarrit_carrito_id_60c4faf8_fk_ecommerce; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_itemcarrito
    ADD CONSTRAINT ecommerce_itemcarrit_carrito_id_60c4faf8_fk_ecommerce FOREIGN KEY (carrito_id) REFERENCES public.ecommerce_carrito(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecommerce_itemcarrito ecommerce_itemcarrit_producto_id_96ba4caa_fk_ecommerce; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_itemcarrito
    ADD CONSTRAINT ecommerce_itemcarrit_producto_id_96ba4caa_fk_ecommerce FOREIGN KEY (producto_id) REFERENCES public.ecommerce_producto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecommerce_pedido ecommerce_pedido_usuario_id_bae8e245_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_pedido
    ADD CONSTRAINT ecommerce_pedido_usuario_id_bae8e245_fk_auth_user_id FOREIGN KEY (usuario_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecommerce_perfilusuario ecommerce_perfilusuario_usuario_id_a4b8e445_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_perfilusuario
    ADD CONSTRAINT ecommerce_perfilusuario_usuario_id_a4b8e445_fk_auth_user_id FOREIGN KEY (usuario_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecommerce_producto ecommerce_producto_categoria_id_8e5a1cdf_fk_ecommerce; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_producto
    ADD CONSTRAINT ecommerce_producto_categoria_id_8e5a1cdf_fk_ecommerce FOREIGN KEY (categoria_id) REFERENCES public.ecommerce_categoria(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecommerce_producto ecommerce_producto_tienda_id_49e5a762_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.ecommerce_producto
    ADD CONSTRAINT ecommerce_producto_tienda_id_49e5a762_fk_auth_user_id FOREIGN KEY (tienda_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecommerce_reseña ecommerce_reseña_producto_id_e3eb4cd3_fk_ecommerce_producto_id; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public."ecommerce_reseña"
    ADD CONSTRAINT "ecommerce_reseña_producto_id_e3eb4cd3_fk_ecommerce_producto_id" FOREIGN KEY (producto_id) REFERENCES public.ecommerce_producto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecommerce_reseña ecommerce_reseña_usuario_id_87c75aa3_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public."ecommerce_reseña"
    ADD CONSTRAINT "ecommerce_reseña_usuario_id_87c75aa3_fk_auth_user_id" FOREIGN KEY (usuario_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: chocolate_user
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_auth_user FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict c0LvLKAbixGx8DweVpl2gkNBGauvloZUWmBdEyCXxdXhVB1gNSCcMEsiA1Nva61

